### PR TITLE
Add FPS slider.

### PR DESCRIPTION
**Pull request by leebickmtu**
Added a slider for FPS during playback.

### CODE REVIEW

**Comment by danielsamuels** [comment]
Hey,

Thanks for the pull request.  It's worth noting that the maximum FPS that the playback system can use is whatever the user's screen refresh rate is, so for the vast majority of people that's going to be 60, for some people it could be 120 or 144.  With that in mind, it might be a good option to see if there's a way to determine what that rate is for a particular user and limit the max accordingly.

I'll checkout the code and merge if it all looks ok, let me know if you want to look into the refresh rate or not, I don't mind either way - happy to take that on.

Thanks,
Dan.

**Comment by leebickmtu** [comment]
I've added detecting the max fps.

**Comment by danielsamuels** [comment]
Thanks! I'm going to take a look and see if I can get it merged in.

**Comment by danielsamuels** [comment]
I made some small changes (mainly in terms of positioning), but this is merged as of 066809d592d8905d89931f1ab318f113334605de. Thank you for your pull request!

**Pull request closed without merging**
